name: CI Tests

on: [ push ]

env:
  CI: true

jobs:

  ci-test:
    runs-on: ${{ matrix.os }}

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 14, 16, 18 ]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      name: git checkout
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v3
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: npm install && npm list --depth=0

    - run: npm run test
